name: C CI/CD with MISRA and Build (fixed cppcheck)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_and_misra:
    runs-on: windows-latest
    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install GCC
      - name: Install GCC (MinGW)
        run: |
          choco install -y mingw make
          refreshenv
          gcc --version

      # 3. Download and setup Cppcheck (official zip)
      - name: Download Cppcheck portable release
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/danmar/cppcheck/releases/download/2.14.0/cppcheck-2.14-win64.zip -OutFile cppcheck.zip
          Expand-Archive cppcheck.zip -DestinationPath cppcheck
          $env:Path += ";$PWD\cppcheck"
          cppcheck\cppcheck.exe --version

      # 4. Run MISRA check
      - name: Run MISRA check (Cppcheck)
        shell: pwsh
        run: |
          echo "Running MISRA compliance analysis..."
          cppcheck\cppcheck.exe --enable=all --std=c11 --suppress=missingIncludeSystem --addon=misra --error-exitcode=1 src 2> cppcheck_report.txt
          echo "---- MISRA check completed ----"
          type cppcheck_report.txt

      # 5. Build
      - name: Build C application
        run: |
          gcc src/Main.c -o main.exe
          echo "Build completed"

      # 6. Upload artifacts
      - name: Upload artifacts (exe + MISRA report)
        uses: actions/upload-artifact@v4
        with:
          name: build-and-misra-results
          path: |
            main.exe
            cppcheck_report.txt
