name: C CI/CD with Static Analysis and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  # -------------------------------------------------
  # 1️⃣ Static Analysis (Cppcheck)
  # -------------------------------------------------
  cppcheck:
    name: Static Analysis (Cppcheck)
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run Cppcheck with include path fix
      - name: Run Cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable: all
          std: c11
          output_file: cppcheck_report.txt
          other_options: "--error-exitcode=1 -I src -I /usr/include -I /usr/lib/gcc/x86_64-linux-gnu/11/include"

      # Upload Cppcheck report
      - name: Upload Cppcheck report
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: cppcheck_report.txt

  # -------------------------------------------------
  # 2️⃣ Build (GCC on Windows)
  # -------------------------------------------------
  build:
    name: Build (GCC on Windows)
    runs-on: windows-latest
    needs: cppcheck  # only runs if analysis passes

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install GCC (MinGW)
      - name: Install GCC (MinGW)
        run: |
          choco install -y mingw make
          refreshenv
          gcc --version

      # Compile your application
      - name: Build C application
        run: |
          echo "Compiling source files..."
          gcc src/Main.c -o main.exe
          echo "Build completed successfully."

      # Upload final build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: main.exe
