name: C CI/CD with MISRA and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}  # allows manual trigger

jobs:
  build_and_misra:
    name: MISRA Check + Build
    runs-on: windows-latest

    steps:
      # -------------------------------
      # 1. Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # 2. Install GCC (MinGW) and Cppcheck
      # -------------------------------
      - name: Install GCC (MinGW) and Cppcheck
        run: |
          choco install -y mingw make cppcheck
          refreshenv
          gcc --version
          cppcheck --version

      # -------------------------------
      # 3. Run MISRA checks using Cppcheck
      # -------------------------------
      - name: Run MISRA check (Cppcheck)
        run: |
          echo "Running MISRA compliance analysis..."
          cppcheck --enable=all --std=c11 --suppress=missingIncludeSystem --addon=misra --error-exitcode=1 src 2> cppcheck_report.txt
          echo "---- MISRA check completed ----"
          type cppcheck_report.txt

      # -------------------------------
      # 4. Build the C application
      # -------------------------------
      - name: Build C application
        run: |
          echo "Building project..."
          gcc src/Main.c -o main.exe
          echo "---- Build completed ----"

      # -------------------------------
      # 5. Upload artifacts
      # -------------------------------
      - name: Upload artifacts (exe + MISRA report)
        uses: actions/upload-artifact@v4
        with:
          name: build-and-misra-results
          path: |
            main.exe
            cppcheck_report.txt
